### ISSUE TITLE
Debugging busted when projectRoot != ${workspaceFolder}

### ISSUE THREAD

**Issue by jb4e** [microsoft/vscode-react-native#1075]
First, thanks for the great extension. Debugging in chrome was becoming quite tiresome. However, it took me a couple hours to get things up and running (mainly because I was looking at the wrong log output). I'm not sure if it's a bug or my misunderstanding/lack of documentation. 

My react-native project is not in my root workspace folder. The directory structure is: 
- MyWorkspaceRoot
    - app (this is the react native app)
    - otherProject1
    - otherProject2

Per https://github.com/microsoft/vscode-react-native/blob/master/doc/customization.md, I added a projectRoot config value of './app' to my workplace settings. 

I then tried to debug with the default "Debug ios" launch config with "cwd": ${workspaceFolder}. This resulted in debug output of: 
```
Could not debug. Seems to be that you are trying to debug from within directory that is not a React Native project root. 
 If so, please, follow these instructions: https://github.com/Microsoft/vscode-react-native/blob/master/doc/customization.md#project-structure. (error code 604)
```

I then tried changing "cwd" to "${workspaceFolder}/app" and tried launching. This resulted in debug output of:
```
 "Could not debug. ENOENT: no such file or directory, open '/Users/jacob/Source/copper/copper/app/.vscode/.react/debuggerWorker.js'"
```
Note that it's looking for the .vscode/.react directory under app, which didn't exist. 

I was able to get things working by manually creating a .vscode/.react directory under app. I think the root problem is that the version check is failing unless cwd is set to ${workspaceFolder}/app because react-native -v is producing:

```
$ react-native -v
react-native-cli: 2.0.1
react-native: n/a - not inside a React Native project directory
```
Expected behavior: 
Things to work without having to manually create the .vscode/.react directory. 

## Software versions
- React-Native VS Code extension version: 0.10.2
- VSCode version: 1.37.0
- OS platform and version: MacOS Mojave 10.14.3 (18D42)
- NodeJS version: 12.7
- React Native version: 0.60.4
- Expo SDK version (include if relevant): N/A

**Comment by SounD120** [comment]
Hi @jb4e and thanks for your feedback! I just tried to reproduce your behaviour with such configuration: 
- RootFolder
    - .vscode (folder with `launch.json` and `settings.json` files)
    - rnapp (React Native app)
    - otherProject1
    - otherProject2

Content of my `settings.json`:
```
{
    "react-native-tools.projectRoot": "./rnapp"
}
```
Content of `launch.json`: 
```
        {
            "name": "Debug iOS",
            "cwd": "${workspaceFolder}",
            "type": "reactnative",
            "request": "launch",
            "platform": "ios"
        }
```
This configuration has started to work in my case just after VS Code reloading.

But this method is a deprecated one, there is a new approach to work with multi-root workspaces in VS Code: https://code.visualstudio.com/docs/editor/multi-root-workspaces
I'd recommend to try out this new approach. It will require to create independent `launch.json` files for each of your projects and then all of them will be availible from one debug configuration list for you workspace.

With respect to the behavior when `cwd` points to folder where `.vscode/.react` is not exist, I was able to reproduce this behaviour and it will be fixed in new extension version.
Please let me know if you have any questions.

**Comment by jb4e** [comment]
Thank you @SounD120 for the tips and fixing the directory creation issue!
