### ISSUE TITLE
Issues debugging async functions

### ISSUE THREAD

**Issue by molant** [microsoft/vscode-react-native#1270]
We've got a few reports of people having issues debugging async functions. I'm opening this issue to keep an eye of those and see if something rings a bell as to what could be going on:

> I'm using the outdated versions of RN: 0.59.10. It would be great to properly support the debugging of `async` functions. In scenarios like `const a = await sth`, I can not set the breakpoint for this line. UI automatically sets the breakpoint to the parent function, which I can not really use. To overcome this I add a line of sync code, like variable declaration after the line I want to debug, and set the breakpoint there

>  Improve the debugging process : mainly with async functions, even when I refresh the debug session, my breakpoints often jumps to unwanted lines.

>  debugging is really tough. especially in async try/catch blocks using TS.

> Being able to step through async functions would be amazing.

**Comment by JiglioNero** [comment]
Hi @molant , with respect to async functions, we tried to reproduce this error this without using an extension but with Google Chrome, but this problem is still reproducible. Most likely the error is in source maps.

![React Native Debugger - Google Chrome 2020-08-11 16-00-14 (online-video-cutter com) (1)](https://user-images.githubusercontent.com/43934531/89906084-9b76a000-dbf3-11ea-8326-bbb3601e30a5.gif)
