### ISSUE TITLE
[Bug] Unable to run Android on Emulator with custom .env file

### ISSUE THREAD

**Issue by webda2l** [microsoft/vscode-react-native#1314]
# 🐛 What is the bug? How can we reproduce it?

1. Project with two ENV files .env and .env.local
2. A .vscode/settings.json file with ```"react-native.android.envFile.simulator": "/home/......./.env.local"```
3. Ctrl-Maj-P "React Native: Run Android on Emulator"

## Expected behavior

```text
...
> Configure project :app
Reading env from: .env.local
...
```

## Debug output

```text
...
> Configure project :app
Reading env from: .env
...
```
</details>

## Environment

* React Native Tools extension version: 0.16.0

**Comment by JiglioNero** [comment]
Hi @webda2l and thanks for reaching us. 
We tried to reproduce this problem the following way:

1. I created `.env.local` and `.env` files:
    ```
    .env.local:
      `TEST1=321`

    .env:
      `TEST1=123`
      `TEST2=123`
    ```
1. Added such parameter in `settings.json` file:
    ```
    {
          "react-native.android.envFile.simulator": "C:/Users/user/VSCodeProjects/HelloApp/.env.local"
    }
    ```
2. Ran `React Native: Run Android on Emulator` with `Ctrl+Shift+P`

Then during the debugging of the extension we checked which environment variables were passed to the packeger.
In the packager start function, custom environment variables are read from the specified file or the `env` parameter in `launch.json` file. In this case, the path to the file is `"C:/Users/user/VSCodeProjects/HelloApp/.env.local"`

![image](https://user-images.githubusercontent.com/43934531/84763519-02515180-afd5-11ea-9bba-336a2f783b58.png)

![image](https://user-images.githubusercontent.com/43934531/84758616-5c9ae400-afce-11ea-8fff-d8ed5687545b.png)

It seems that the environment variables from the specified file are successfully passed to the packager.

Could you please check the full path to the `.env.local` file and `settings.json` structure?

**Comment by webda2l** [comment]
Hi @JiglioNero, thanks for looking after this.

I'm on Ubuntu and full path is right.
```
david@laptop:~$ cat /home/david/Works/Project/app/.vscode/settings.json 
{
    "react-native.android.envFile.simulator": "/home/david/Works/Project/app/.env.local"
}
david@laptop:~$ ll /home/david/Works/Project/app/.env.local
-rw-rw-r-- 1 david david 820 juin  10 14:44 /home/david/Works/Project/app/.env.local

```

This project is open as a Workspace in VScode with three directories, 'app' and two others.
I tested to add the settings ```"react-native.android.envFile.simulator": "/home/david/Works/Project/app/.env.local"``` at workspace level, in addition to the ```app folder``` level, but, without effects.. 
I tested too, to open a distinct and only VScode with the ```app``` directory only,  but same problem, ```Reading env from: .env``` and not ```.env.local```

I will try later to debug as well the packager start function.

**Comment by JiglioNero** [comment]
@webda2l, we tried to reproduce this issue using Workspace:

Scenario number 1
1. Created Workspace and added two projects there.

![image](https://user-images.githubusercontent.com/43934531/85023647-b2fa5500-b17d-11ea-9e87-2ac8566bc4e2.png)

2. Added `.env.local` to one of the projects and specified it in `settings.json`

    ```
    {
          "react-native.android.envFile.simulator": "C:/Users/user/VSCodeProjects/HelloApp/.env.local"
    }
    ```

3. Selected `React Native: Run Android on Emulator` with `Ctrl + Shift + P` and ran one of the projects
4. In this case, the data from the `.env.local` is passed to the application and packager.

Scenario number 2
1. Created Workspace and added two projects there.
2. Moved `.env.local` to the Workspace root folder.
3. Changed the path to `.env.local` in` settings.json`.

    ```
    {
          "react-native.android.envFile.simulator": "C:/Users/user/VSCodeProjects/.env.local"
    }
    ```

4. Selected `React Native: Run Android on Emulator` with` Ctrl + Shift + P` and ran one of the projects
5. In this case, the extension correctly found the `envFile` and passed the parameters specified in `.env.local` to the packager

Could you please provide us with a demo project with this problem so that we can reproduce the error? This will help us to investigate the issue faster.

**Comment by webda2l** [comment]
@JiglioNero Thanks.
Sure, fresh push here https://github.com/webda2l/reactnative-debug/tree/master

**Comment by webda2l** [comment]
I debugged as well your extension and env variable passed to packager is well uptodate with envFile values.

So if https://github.com/luggit/react-native-config works well with ```ENVFILE=.env.local node_modules/.bin/react-native run-android```, it is incompatible with the packager launching way of this extension (node.ChildProcess env param).

https://github.com/luggit/react-native-config seems like the best module anyway..
Thanks, I close.

**Comment by JiglioNero** [comment]
We are glad that you have solved the problem. As for this library, `envFile` import occurs here https://github.com/luggit/react-native-config/blob/master/ios/ReactNativeConfig/ReadDotEnv.rb for the iOS platform and here https://github.com/luggit/react-native-config/blob/master/android/dotenv.gradle for the Android platform. My advise is to explore the settings of this library, maybe it can provide the necessary functionality.
