### ISSUE TITLE
[Bug] Expo SDK 38 not supported?

### ISSUE THREAD

**Issue by GollyJer** [microsoft/vscode-react-native#1317]
I followed the directions to get my expo app set up for debugging. However, when running I get the following. _It works as expected when running via `expo start`._

<img src=https://user-images.githubusercontent.com/689204/84575738-64efe680-ad64-11ea-97b9-1837b77bb03f.png width=280>

**Comment by GollyJer** [comment]
OK, now sure how my app.json got set to expo v38 when it isn't even out yet. 
Set back to 37 and all good.

**Comment by GollyJer** [comment]
Actually, I think this is a bug... React Native Tools added a `"sdkVersion": "38.0.0"` entry to my `app.json` file. 

Expo no longer requires an sdk entry.

**Comment by RedMickey** [comment]
Hi @GollyJer and thanks for reaching us. The extension uses `@expo/xdl` package to get an Expo SDK version. We investigated this issue and found out that the function of getting Expo SDK version works incorrectly in `@expo/xdl` package. Expo has added Expo SDK v38 to SDK versions, but it hasn't been released yet. For now the function returns the latest version of SDK, so we get SDK 38 instead of 37. We opened [the issue about this bug](https://github.com/expo/expo-cli/issues/2257) in `expo/expo-cli` repository.
But until Expo fixes this bug, please, replace`"sdkVersion": "38.0.0"` with `"sdkVersion": "37.0.0"` manually in `app.json` file if you face this problem again.

**Comment by RedMickey** [comment]
Hi @GollyJer Expo has fixed this bug in a [new version](https://www.npmjs.com/package/@expo/xdl/v/57.9.25) of the `@expo/xdl` package. To update the current version of this package on your side you just need to reinstall the extension and then relaunch VS Code editor.
