### ISSUE TITLE
The debugger / React Native was hang if too many console.log messages output to Debug Console

### ISSUE THREAD

**Issue by ccl0504** [microsoft/vscode-react-native#1335]
## Actual Behavior
1. The debugger / React Native was hang if too many console.log messages output to Debug Console (when enabled debug JS remotely) on Android emulator
2. It's no problem if JS remote debug was disabled ( the console.log messages were outputted to Output tab.
3. Same test code on Mac + iPhone emulator was OK
4. I tried timer callback function to do console.log output for 1 time per second, the debugger was still hang

## Expected Behavior
1. Debugger / React Native won't hang

## Software versions
- React-Native VS Code extension version: 0.16.1
- VSCode version: 1.46.1
- OS platform and version: Windows 10 Pro 1909 
- NodeJS version: 
- React Native version: 0.62.2
- Expo SDK version (include if relevant):

[App.js](https://1drv.ms/u/s!Aio6qXCD_wsdqh0sL2pDQRfQ8oG_)

**Comment by SounD120** [comment]
Hi @ccl0504 and thanks for your question. React Native Tools debugger is based on debugging via local Node.js process. As we found out Node.js has some problems with large amounts of IO due to architectural features: https://github.com/nodejs/node/issues/6379. 
So I recommend to not overload the debugger thread by non-blocking IO like `console.log`.
