### ISSUE TITLE
--proxy option in react native windows

### ISSUE THREAD

**Issue by asklar** [microsoft/vscode-react-native#1411]
https://github.com/microsoft/vscode-react-native/blob/30806f65a65b8aff36b6dfdfea8e94af513e5fb3/src/extension/windows/windowsPlatform.ts#L46-L52

The --proxy option was renamed in RNW to --remote-debugging: https://github.com/microsoft/react-native-windows/commit/8f12940f753cee4f1ad8d4da7d9d3a3e755b9241

Also I'm not sure the logic to compare against 0.63 makes sense? can someone explain what this is supposed to do? Why enable debugging if RNW version is <63?

**Comment by asklar** [comment]
Related: https://github.com/microsoft/react-native-windows/issues/6091

**Comment by SounD120** [comment]
Hi @asklar . Right now proxy parameter is disabled for the applications which are greater or equal than 0.63. You said that the parameter has been renamed in RNW CLI. Does it depend on the RNW version, and from which exact version this argument was changed? I think we can add it instead of `--proxy` for versions >= 0.63.0. What do you think?

**Comment by asklar** [comment]
@SounD120 yes I think you can use --remote-debugging on 63 and up - paging @rectified95 to confirm

**Comment by SounD120** [comment]
@asklar FYI support for macOS debugging will be added soon after the 1.0.0 version release. Please see #1409.

**Comment by rectified95** [comment]
I made the check-in on June 8th, don't really know how to check what exact release that's in, but 0.63 sounds about right
