### ISSUE TITLE
[Bug] [Error] XDLError: ValidationError: "devClient" is not allowed

### ISSUE THREAD

**Issue by GollyJer** [microsoft/vscode-react-native#1482]
I'm getting this error when trying to debug an Expo project.
```
[Error] XDLError: ValidationError: "devClient" is not allowed
```

The project previously worked without issue. Is this possibly connected to Expo v40? I can't remember if I've used debugging since updating a few weeks back.

Thanks!

**Comment by HamzaIraoui** [comment]
> I'm getting this error when trying to debug an Expo project.
> 
> ```
> [Error] XDLError: ValidationError: "devClient" is not allowed
> ```
> 
> The project previously worked without issue. Is this possibly connected to Expo v40? I can't remember if I've used debugging since updating a few weeks back.
> 
> Thanks!

@GollyJer **me also**  , i get the same error

**Comment by HamzaIraoui** [comment]
> I'm getting this error when trying to debug an Expo project.
> 
> ```
> [Error] XDLError: ValidationError: "devClient" is not allowed
> ```
> 
> The project previously worked without issue. Is this possibly connected to Expo v40? I can't remember if I've used debugging since updating a few weeks back.
> 
> Thanks!

- [ ]  i solve my problem by remove **.expo** in my project folder

**Comment by JiglioNero** [comment]
Hi @GollyJer and thank you for the report. We have faced the similar problem while debugging an Expo SDK 40 project on an iOS simulator. Now we are investigating this issue. Could you please tell us which OS you are using and and which mobile platform you use for running the Expo application on (iOS or Android)?

**Comment by GollyJer** [comment]
- Windows 10
- Android (real device) and iOS (real device)

```json
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Debug Expo Project",
      "cwd": "${workspaceFolder}",
      "type": "reactnative",
      "request": "launch",
      "platform": "exponent",
      "openExpoQR": false,
      "expoHostType": "local"
    }
  ]
}
```

**Comment by minaelee** [comment]
You can see that settings.json (which lives in the .expo folder) was updated to include two new properties: `scheme` and `devClient` in this commit on December 12:
https://github.com/expo/expo-cli/commit/9e3cb1eb154d689d3c7fbe18345e6b32cf59ad7b#diff-412633fe3f2f4d6e1c8e75ab06fc6711542ec887fe07765f2aadbc0af93b381a

I have been reliably able to recreate this issue via the following steps:
- Globally add/install expo-cli so that the latest is installed. (updated 7 days ago, includes the above commit)
- Scaffold out a new starter project, e.g. `expo init test -t blank`
- `expo start` then ctrl-c. This creates a settings.json file in the .expo folder that contains the new scheme property, but not yet the devClient property.
- `expo start` again. It is at this point that I see a `devClient=false` property inside settings.json. 
- ctrl-c then downgrade global expo-cli to @3, so that the latest 3.x version is installed.
- `expo start` again and the ValidationError: "devClient" is not allowed error message is seen, because expo-cli is using the cached settings.json from .expo. 
- Deleting the .expo folder at this point and forcing expo-cli to recreate it at the next expo-start will resolve the issue. 
-  Alternatively, updating to the latest expo-cli version should also resolve this issue, but that is not always desirable as it can cause other compatibility issues.

**Comment by RedMickey** [comment]
@minaelee, thank you for the investigation, we also came to the same conclusion.

Under the hood the extension uses `@expo/xdl` package to run Expo apps. The extension downloads the latest version of the package on the fist start of Expo debugging and then uses the cached package. Due to [the latest changes in Expo-CLI](https://github.com/expo/expo-cli/commit/9e3cb1eb154d689d3c7fbe18345e6b32cf59ad7b#diff-412633fe3f2f4d6e1c8e75ab06fc6711542ec887fe07765f2aadbc0af93b381a), the old cached `@expo/xdl` package mightn't support the added parameters in `.expo/settings.json` file. The easiest way to update `@expo/xdl` package on your side is to reinstall the extension.

@GollyJer Could you please reinstall the extension the following way and then try to debug an Expo app again?
* Uninstall the extension
* Close VS Code
* Open VS Code
* Install the extension

Please let us know about your results.

**Comment by GollyJer** [comment]
@RedMickey That worked. Thanks!

**Comment by NorfeldtAbtion** [comment]
in my case it was because I was running node 10 via nvm instead of node 14

**Comment by MorenoMdz** [comment]
> in my case it was because I was running node 10 via nvm instead of node 14

Hey, having the same issue here configuring a new Mac M1. The thing is the version of Expo I use don't support Node 14. What did you do?
