### ISSUE TITLE
[Feature] Custom color for Output Console Panel

### ISSUE THREAD

**Issue by zxccvvv** [microsoft/vscode-react-native#1525]
# 🚀 Feature request

What do you want to be added?

Custom colors for `Output Panel` to make it easier for debugging, since current `Output Panel` text is only show white color

### **Current `Output Panel`**

<img width="1403" alt="Screen Shot 2021-03-12 at 16 35 58" src="https://user-images.githubusercontent.com/19633881/110921340-08504500-8351-11eb-8478-02b10de0de7a.png">

[`Debug Console Panel`](https://code.visualstudio.com/api/references/theme-color#debug-icons-colors) has this benefit:

- `debugConsole.infoForeground:` Foreground color for info messages in debug REPL console.

- `debugConsole.warningForeground:` Foreground color for warning messages in debug REPL console.

- `debugConsole.errorForeground:` Foreground color for error messages in debug REPL console.

- `debugConsole.sourceForeground:` Foreground color for source filenames in debug REPL console.

I hope we can use similar setup for `Output Console Panel` too,

### Finding possible duplicated issue:
#1272 https://github.com/microsoft/vscode/issues/11005

### Trying
I have tried to use [`Styling Console Output`](https://developer.mozilla.org/en-US/docs/Web/API/console#usage)
```js
console.log("This is %cMy stylish message", "color: yellow; font-style: italic; background-color: blue;padding: 2px");
```

but all text is printed out
<img width="1380" alt="Screen Shot 2021-03-12 at 17 00 16" src="https://user-images.githubusercontent.com/19633881/110924263-6d596a00-8354-11eb-916c-2cde12977084.png">

currently i've craete my own snippet to create custom console.log like this:
```
{
	"Print to console": {
		"scope": "javascript,typescript",
		"prefix": "csl",
		"body": [
			"console.log('[${TM_FILENAME_BASE}] ${1:text}', ${0:data})",
		],
		"description": "Log output to console"
	}
}
```
IMHO this help me to control which file is use the console.log, but it's not enough when print large text (e.g. JSON, networking , warning)

_Sorry my english is not good_

## What scenarios will this solve?

What will this allow you to do? Will this benefit other developers?
short answer is Yes

**Comment by JiglioNero** [comment]
Hi @zxccvvv and thanks for reachig us. We have already investigated the similar [issue](https://github.com/microsoft/vscode-react-native/issues/1272) and started implementing it in this [PR](https://github.com/microsoft/vscode-react-native/pull/1385), by defining the language and grammar for the output channel. But we faced some incorrect behavior, in case several extensions with output colorizing feature are working at the same time: at the moment we cannot specify the extension to colorize the concrete output, so another extension can colorize the output of React Native Tools.

We found out, that for now the functional to control which extension should colorize logs has not been implemented yet. In VS Code repositore there is the [issue](https://github.com/microsoft/vscode/issues/19561) about that problem. So we decided to wait until the problem is resolved to avoid incorrect colorizing.

However, we can provide you the version of React Native Tools extension with the current implementation of this feature. You can install and try that version following these steps:
1. Download and unzip compiled extension [VSIX](file).
2. Uninstall extension
3. Close VS Code
4. Open VS Code
5. Click Extensions -> Views and More Actions... -> Install from VSIX... And select the downloaded VSIX

**Comment by zxccvvv** [comment]
Hi @JiglioNero, thank you for an awesome extension,
i've been implemented custom vscode react native extension as suggested,
and it looks good at the moment,

but can i change the default of colors that have been defined?
or even customize the color something like this:
```
{
  'string': 'color (HEX,RGB[A])',
  'url': 'color (HEX,RGB[A])',
  'TAG': 'color (HEX,RGB[A])'
}
```

cause it's still not look good for long logging

**Comment by JiglioNero** [comment]
Hi @zxccvvv , we added the ability to customize the React Native Tools output logs. For now it is implemented via `editor.tokenColorCustomizations` parameter and `textMateRules` in `settings.json` file. You can find more info about color tags [here](https://github.com/microsoft/vscode-react-native/pull/1385#issuecomment-802772310).
For now we’ve decided to postpone further implementation of this feature and wait until VS Code adds ability to colorize specific output channels (https://github.com/microsoft/vscode/issues/19561). In the future we’ll also try to add configuration of logs colors to the extension settings instead of the current approach.
Here is the [VSIX](https://github.com/microsoft/vscode-react-native/files/6171392/vscode-react-native-1.4.1.vsix.zip) with the current implementation of logs colors customization.

**Comment by zxccvvv** [comment]
Closed since the current `VSIX` approach my expected result,

Thank You @JiglioNero
