### ISSUE TITLE
Why bulid failed?

### ISSUE THREAD

**Issue by yuyuyoyo** [microsoft/vscode-react-native#1590]
# 🐛Why build failed?

I run **react-native run-android** in VS code on powershell and then this show.... 

![image](https://user-images.githubusercontent.com/85676324/121837894-ecb65b00-cd00-11eb-9b33-4f9b60026cc1.png)
![image](https://user-images.githubusercontent.com/85676324/121837995-0192ee80-cd01-11eb-9aaa-be92f7669203.png)
![image](https://user-images.githubusercontent.com/85676324/121838010-09eb2980-cd01-11eb-86be-130417ebf81f.png)

## How I could be solved the error?

I want expecting to Build successful!!

* React Native Tools extension version: 2.0.1

**Comment by RedMickey** [comment]
Hi @yuyuyoyo and thanks for reaching us.
It seems that there is some misconfiguration in your development environment.
It would be helpful if you share with us your current environment settings, so we could check them and investigate the issue faster. Could you please run the following commands and send us their outputs?

* `npx react-native doctor` or `npx expo doctor` if your project is using Expo:

```text
PASTE OUTPUT OF `npx react-native doctor` or `npx expo doctor`
```

* `npx envinfo`

```text
PASTE OUTPUT OF `npx envinfo`
```

Could you please also send us the version of the `react-native` dependency from your `package.json` file?

In accordance with [the official React Native documentation](https://reactnative.dev/docs/environment-setup), I'd recommend you to use `npx react-native` commands instead of just `react-native`.

**Comment by RedMickey** [comment]
@yuyuyoyo Just a friendly ping on this.

**Comment by JiglioNero** [comment]
Close it due to inactivity
