### ISSUE TITLE
[Bug] Can't continue debugging React Native TypeScript app once breakpoint is hit

### ISSUE THREAD

**Issue by lukaspechar** [microsoft/vscode-react-native#1598]
adding reference to original post on VS Code repository.

https://github.com/microsoft/vscode/issues/126354#issue-921180577

**Comment by shivsuthanmhub** [comment]
Yes facing the same issue and it's getting hanged in the debug session.

**Comment by canpoyrazoglu** [comment]
Yup, as the author of the linked issue on Vscode repo, I confirm this bug as well. And the Vscode team, after investigation said that it's caused by the extension even though it started occuring after updating Vscode (more info available on the first comment's linked issue).

**Comment by JiglioNero** [comment]
Hi @lukaspechar , We have investigated the [issue](https://github.com/microsoft/vscode/issues/126354#issue-921180577) which is described in vscode repository. Indeed, the error is not reproducible on version `1.56.2`. So most likely the error caused by vscode changes in version `1.57.1`. The error related to trace occurred due to the fact that a value was entered not from proposed variants. To display CDP Proxy logs, you may set the `verbose` value for the `trace` option in the debug configuration:
```
"configurations": [
        {
            ...
            "trace": "verbose"
        }
    ]
```

There are CDP Proxy logs for vscode `v1.56.2`:
[vscode-1.56.2.txt](https://github.com/microsoft/vscode-react-native/files/6686642/vscode-1.56.2.txt)

![vscode-1 56 2](https://user-images.githubusercontent.com/43934531/122763808-6e7d2a00-d2a7-11eb-99fd-090dfdc03cfb.gif)

There are CDP Proxy logs for vscode `v1.57.1`:
[vscode-1.57.1.txt](https://github.com/microsoft/vscode-react-native/files/6686652/vscode-1.57.1.txt)

![vscode-1 57 1](https://user-images.githubusercontent.com/43934531/122763921-8fde1600-d2a7-11eb-99f1-cafb3f744764.gif)

**Comment by lukaspechar** [comment]
@JiglioNero thanks for your reply. Yes, that is exactly what I em experiencing... that hang in the variables window. It does move on after a very long time but not always. Is this really an issue with `vscode-react-native`? Any suggested fixes? Thanks

**Comment by JiglioNero** [comment]
@lukaspechar After some more investigation, we noticed that the hang occurs while processing the result of the Debugger.getScriptSource method. Based on the CDP Proxy logs, this method was not called in vscode `v1.56.2`.

![image](https://user-images.githubusercontent.com/43934531/122797885-9f218b80-d2c8-11eb-8cbb-141955d1292e.png)

It seems that the problem caused by updating `js-debug` version, which `React Native Tools` uses to debug applications. You may open an issue in the [`js-debug` repository](https://github.com/microsoft/vscode-js-debug). For now, there is a workaround to downgrade the version of your vscode up to version `v1.56.2`. Feel free to contact us if you have any other questions or need our help in solving this problem.

**Comment by lukaspechar** [comment]
Thanks for the response, I'll submit an issue on the [js-debug](https://github.com/microsoft/vscode-js-debug) repository. I've downgraded already and I've also disabled auto-update for vscode.
