### ISSUE TITLE
[Feature] What is proper safe way to stop the emulator, metro, etc ???

### ISSUE THREAD

**Issue by gfmoore** [microsoft/vscode-react-native#1647]
# 🚀 Feature request

What do you want to be added?

## What scenarios will this solve?

What will this allow you to do? Will this benefit other developers?

I currently close the Output by clicking on the x, does this close things down safely? Then I remove the app from the emulator. Do I need to do that or will restarting Run Android on Emulator overwrite the app or add a new one? 

I'd like a task (ok F1 task) that does a closedown properly please clearing everything up, closing the app (and removing it), closing Metro, closing anything else that might be running!!

Thanks,

Gordon

**Comment by RedMickey** [comment]
Hi @gfmoore, thanks for reaching us. It's not necessary to remove the RN application from the emulator before the next run of `Run Android on Emulator` command or a debugging scenario, because the previously installed application will be overwritten by the new version of the app automatically.

> I currently close the Output by clicking on the x, does this close things down safely?

Closing Output panel doesn't stop running processes.

In case the Metro packager was launched in the extension (while executing a Command Palette command or a debugging scenario or by clicking on `React Native Packager` item in the status bar), you can stop it by running `Stop Packager` command or just clicking on `React Native Packager` item with "stop" icon in the status bar.
![image](https://user-images.githubusercontent.com/33267199/130046908-14cb8140-9966-4c09-b053-45f4620657bf.png)
![image](https://user-images.githubusercontent.com/33267199/130046932-41e230b9-6652-4353-9ede-1e480d6371bd.png)

**Comment by gfmoore** [comment]
That's great. Once again thank so much. :)
