### ISSUE TITLE
[Bug] Debug Directory Includes Internal Files Too

### ISSUE THREAD

**Issue by ezranbayantemur** [microsoft/vscode-react-native#1663]
Hi there;

I'm not sure is it real bug or something that I missed, sorry in advance if it's mistake but the issue is really makes debugging process hard.

When starting the debugging, inspected directory goes to the internal files. I mean when I leave a breakpoint to my `src/bla/bla/SomeFile.tsx` file, I want debugging process to stay only my `src/` directory. But it goes to internal files like;
- `node_modules/react/cjs/react.development.js`
- `node_modules/react-native/Libraries/Renderer/implemetations/ReactNativeRenderer-dev.js`
or anything related.

I'm leaving minimal example video of this issue

https://user-images.githubusercontent.com/42299721/133395743-b9b6e070-f2ee-41be-84a3-f4145246e866.mov

Is there any way to handle this?

**Comment by RedMickey** [comment]
Hi @ezranbayantemur and thanks for reaching us. It seems that this is the expected behavior of the debugger when you try to use "Step Into" action on an RN library function. To fix this behavior, it's possible to exclude certain files and directories while debugging, so that the debugger doesn't consider them. For this purpose the extension provides [the `skipFiles` parameter for debugging configurations](https://github.com/microsoft/vscode-react-native#debugger-configuration-properties).
You can try to add the `skipFiles` parameter with the following patterns to your debugging configuration to exclude `node_modules` and `node_internals` from the list of files for debugging:
```
    "skipFiles": [
        "<node_internals>/**",
        "${workspaceFolder}/node_modules/**"
    ]
```

**Comment by ezranbayantemur** [comment]
I tried it and it works perfectly @RedMickey, thank you so much for your quick response, you rock! 🍻
