### ISSUE TITLE
[Bug] Failed to start the React Native packager (error code 106)

### ISSUE THREAD

**Issue by mjstelly** [microsoft/vscode-react-native#1678]
# 🐛 What is the bug? How can we reproduce it?

I am unable to launch RN packager from within VSC. I tried all the steps listed in[ this thread from 2 years ago
](https://github.com/microsoft/vscode-react-native/issues/1012) with no success. I created a new vanilla RN app. 
1. Uninstalled RN Tools
2. Reinstalled RN Tools v1.7.0
3. Closed VSC
4. Created vanilla react native project using `react-native init rntest` from terminal
5. Opened VSC
6. Before launching app, from the command palette, selected `React Native: Start Packager`

## Expected behavior

React Native (metro) packager would launch and display status in the status bar.

## Debug output

<details>
<summary>Debug Console</summary>

```text
No output
```
</details>

<details>
<summary>React Native output channel</summary>

```text
[Error] Failed to start the React Native packager (error code 106)

Stack: Error: Failed to start the React Native packager (error code 106): Error while working with workspace: Current workspace does not contain React Native projects. (error code 710)
	at Function.getWrappedError (/Users/mikestelly/.vscode/extensions/msjsdiag.vscode-react-native-1.7.0/dist/rn-extension.js:21:67062)
	at Function.wrapError (/Users/mikestelly/.vscode/extensions/msjsdiag.vscode-react-native-1.7.0/dist/rn-extension.js:21:60172)
	at /Users/mikestelly/.vscode/extensions/msjsdiag.vscode-react-native-1.7.0/dist/rn-extension.js:21:59745
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
</details>

<details>
<summary>Developer Tools console</summary>

```text
console.ts:137 [Extension Host] (node:4616) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.(Use `Code Helper (Renderer) --trace-deprecation ...` to show where the warning was created)
v @ console.ts:137
mainThreadExtensionService.ts:63 [[object Object]]s.tmpDir is not a function
$onExtensionRuntimeError @ mainThreadExtensionService.ts:63
mainThreadExtensionService.ts:64 TypeError: s.tmpDir is not a function
	at e._sendFirstFileOnDisk (vscode-file://vscode-app/Users/mikestelly/.vscode/extensions/msjsdiag.vscode-react-native-1.7.0/dist/rn-extension.js:1)
	at Timeout._onTimeout (vscode-file://vscode-app/Users/mikestelly/.vscode/extensions/msjsdiag.vscode-react-native-1.7.0/dist/rn-extension.js:1)
	at listOnTimeout (internal/timers.js:554)
	at processTimers (internal/timers.js:497)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:64
```
</details>

## Environment

Please tell us about your system and your project:

* `npx react-native doctor` or `npx expo doctor` if your project is using Expo:

```text
Common
 ✓ Node.js
 ✓ yarn
 ✖ Watchman - Used for watching changes in the filesystem when in development mode
   - Version found: 2021.09.13.00
   - Version supported: 4.x

Android
 ✓ JDK
 ✓ Android Studio - Required for building and installing your app on Android
 ✖ Android SDK - Required for building and installing your app on Android
   - Versions found: N/A
   - Version supported: 30.0.2
 ✓ ANDROID_HOME

iOS
 ✓ Xcode - Required for building and installing your app on iOS
 ✓ CocoaPods - Required for installing iOS dependencies
 ● ios-deploy - Required for installing your app on a physical device with the CLI
```

* `envinfo`:

```text

  System:
    OS: macOS 11.6
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 4.28 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.0 - /usr/local/bin/node
    npm: 6.14.15 - /usr/local/bin/npm
    Watchman: 2021.09.13.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
    Homebrew: 3.2.14 - /usr/local/bin/brew
    pip3: 21.2.4 - /usr/local/bin/pip3
    RubyGems: 3.0.3 - /usr/bin/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 4.2.1 - /usr/bin/gcc
    Git: 2.30.1 - /usr/bin/git
    Clang: 12.0.5 - /usr/bin/clang
  Servers:
    Apache: 2.4.48 - /usr/sbin/apachectl
  Virtualization:
    Docker: 20.10.7 - /usr/local/bin/docker
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 31.0.0
      System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7678000
    Nano: 2.0.6 - /usr/bin/nano
    VSCode: 1.60.2 - /usr/local/bin/code
    Vim: 8.2 - /usr/bin/vim
    WebStorm: 2021.2.1
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Java: 1.8.0_292 - /usr/bin/javac
    Perl: 5.30.2 - /usr/bin/perl
    PHP: 7.3.29 - /usr/bin/php
    Python: 2.7.16 - /usr/bin/python
    Python3: 3.9.7 - /usr/local/bin/python3
    Ruby: 2.6.3 - /usr/bin/ruby
  Databases:
    SQLite: 3.32.3 - /usr/bin/sqlite3
  Browsers:
    Brave Browser: 93.1.29.81
    Chrome: 93.0.4577.82
    Firefox: 91.0.2
    Safari: 15.0
```

* React Native Tools extension version: `1.7.0`
* Expo SDK version (if applicable): NA

**Comment by etatanova** [comment]
Hi @mjstelly and thanks for reaching us. We tried to reproduce this problem and got the same error if the Project Root parameter (`react-native-tools.projectRoot`) in the extension settings was set and had an incorrect path (didn’t refer to an RN project). Could you please check if this parameter is changed in your settings (_Settings -> Extensions -> React Native configurations_ or in the `settings.json` file)? If yes, please try to remove it or change to the right project root folder if it’s incorrect.
If `projectRoot` is correct or absence, could you please do the following:
1. Set the extension log level to `Trace`. You can change the extension log level by adding the `settings.json` file to the `.vscode` folder in your project with the following content:
    ```
    {
        "react-native-tools.logLevel": "Trace"
    }
    ```
2. Reload VSCode.
3. Run `Start Packager` command.

Please send us new logs from `React Native` output channel.

**Comment by mjstelly** [comment]
Aw crap. I celebrated too soon. The proposed solution worked for the test app, not the actual project. Now, when I try to set the tools loglevel, like this `"react-native-tools.logLevel": "Trace"`, VSC throws the following error on the value: `Incorrect type. Expected "enum".` Relaunching VSC doesn't resolve it. The value is not accepted.

**Comment by mjstelly** [comment]
It seems the loglevel setting error, mentioned above, is a false negative. 
Below is the RN `output` channel contents. However, what I noticed about this output is that on the line `[Debug] react-native package version is not found in...`the extension is looking in the parent folder (redacted for NDA reasons), **_not_** the RN folder despite the fact that the editor is clearly opened in the correct subfolder. The actual code resides in `projects/parent/rn-code-folder` not `projects/parent`. I think that is the core of the isse.

```
[Debug] Begin to activate...
[Debug] Extension version: 1.7.0
[Debug] Projects found: 1
[Debug] Add project: /Users/mikestelly/projects/<name-redacted>
[Debug] React Native version: errorUnknown
[Debug] react-native package version is not found in /Users/mikestelly/projects/<name-redacted>. Reason: errorUnknown
[Debug] Run command: startPackager

[Error] Failed to start the React Native packager (error code 106)
Stack: Error: Failed to start the React Native packager (error code 106): Error while working with workspace: Current workspace does not contain React Native projects. (error code 710)
	at Function.getWrappedError (/Users/mikestelly/.vscode/extensions/msjsdiag.vscode-react-native-1.7.0/dist/rn-extension.js:21:67062)
	at Function.wrapError (/Users/mikestelly/.vscode/extensions/msjsdiag.vscode-react-native-1.7.0/dist/rn-extension.js:21:60172)
	at /Users/mikestelly/.vscode/extensions/msjsdiag.vscode-react-native-1.7.0/dist/rn-extension.js:21:59745
	at processTicksAndRejections (internal/process/task_queues.js:93:5)

```

**Comment by etatanova** [comment]
> It seems the loglevel setting error, mentioned above, is a false negative.

Yes, that error about `Trace` is just a warning, it's ok.

Extension considers folder as a React Native project if this folder contains the `react-native` dependency either in `node_modules` or in the `package.json` file.

Project Root parameter (`react-native-tools.projectRoot`) in the extension settings (_Settings -> Extensions -> React Native configurations_ or in the `settings.json` file) assumes a subfolder in which the React Native project is located.

I have created and configured [the sample project](https://github.com/etatanova/test-project) with similar structure: `test-project/parent/rntest`.

- When I run command `Start Packager` from the [`test-project`](https://github.com/etatanova/test-project) folder (`projects` folder in your structure) it throws the same error as in your first case because this folder doesn’t contain the `react-native` dependency neither in `node_modules` nor in the `package.json` file in this folder. I [set](https://github.com/etatanova/test-project/blob/main/.vscode/settings.json#L3) the Project Root parameter to `"parent/rntest"` in the extension settings. After that the extension parses this parameter correctly.
- When I run it from the [`parent`](https://github.com/etatanova/test-project/tree/main/parent) folder (also `parent` in your structure) it throws the same error as in your second case for the same reason as in the first case. Then I [set](https://github.com/etatanova/test-project/blob/main/parent/.vscode/settings.json#L3) the Project Root parameter to `"rntest"`. And the packager was correctly started.
- When I run the command from the [`rntest` ](https://github.com/etatanova/test-project/tree/main/parent/rntest)folder (`rn-code-folder` in your structure) it works ok without any additional configuration.

Does your folder with RN project (`projects/parent/rn-code-folder`) have `react-native` dependency either in `node_modules` or in the `package.json` file?

If the `/Users/mikestelly/projects/<name-redacted>` folder doesn’t contain `react-native` dependencies, it’s needed to add the Project Root parameter with a (relative) path to RN project folder to start the packager.

**Comment by mjstelly** [comment]
I've since discovered another problem vector. The project uses Yarn Workspaces, but is incorrectly configured. That may have something to do with the `error while working with workspace` issue I'm encountering. I'll test your various examples.

**Comment by mjstelly** [comment]
It seems I misunderstood the folder structure. It's `repo-root` (cloned from remote) > 'multi-tenant-project-root' > and 2 child folders 'app' and 'design-system' which are supposed to implement yarn workspaces. I tried your examples with no success. I'm investigating the workspace misconfiguration as a possible root cause of this problem because it involves separation of concerns for the `node_modules`.

**Comment by mjstelly** [comment]
It's worth noting that VSC is launched from the `project-root` folder, then `app` should be the child folder. So when I set the project root to `./app`, where `app` node_modules exist,  I get:
```
[Debug] React Native version: errorUnknown
[Debug] react-native package version is not found in /Users/mikestelly/projects/root/project-root/app. Reason: errorUnknown
```
The same occurs if I use the absolute path.

**Comment by etatanova** [comment]
@mjstelly It seems our test project doesn't fully represent the configuration features of your project. Could you please create and send us a minimal demo project (with a similar structure and configuration to your original project) with this problem, so we could reproduce it? This would be very helpful for us to investigate the issue faster.

**Comment by mjstelly** [comment]
This analysis becomes more convoluted by the day. I'm no longer sure that it is a RNT problem, but more of a yarn workspace issue. So, I'll close this for now. If, after I sort this out, the issue still points to RNT, I'll submit a new issue. Thanks for your patience.

**Comment by RedMickey** [comment]
Hi @mjstelly, I tried to reproduce the issue in a monorepo project with yarn workspaces. Below is a screenshot with the project structure and my configuration of `projectRoot`:
![Screen Shot 2021-10-06 at 11 29 03](https://user-images.githubusercontent.com/33267199/136168344-944ec21a-d6af-447c-a498-74d69e814b59.png)
In the `projectRoot` parameter I pointed the folder which contains the `package.json` file with the `react-native` dependency. Actually this folder doesn't contain the `react-native` package in `node_modules` ( the`react-native` package is located in `node_modules` in the monorepo project root folder), but the extension parses the `package.json` file and can recognize this folder as an RN project. This folder also contains React Native CLI binary file, so the extension can use it to run the `react-native start` command. I tried to run `React Native: Start Packager` command, and the packager launched successfully. I believe this solution could be helpful in your case.
If this issue is still relevant for you, could you please try to specify the folder that contains the `package.json` file with the `react-native` dependency in the `projectRoot` parameter and try to start packager again?
