### ISSUE TITLE
[Bug] Debug in Exponent Fails -- Dependencies

### ISSUE THREAD

**Issue by JeffreyWardman** [microsoft/vscode-react-native#1753]
Running Debug in Exponent fails when trying to npm install xdl (which is present globally) (error code 303). Expo doctor and npx react-native doctor return two different results (expo looks fine but npx react-native fails). 

Machine:
Linux
Android Studio, VSCode installed with snap.

expo doctor
```
🎉 Didn't find any issues with the project!
```

npx react-native doctor 
```
Common
 ✓ Node.js
 ✓ npm

Android
 ✖ JDK
   - Version found: N/A
   - Version supported: >= 8
 ✖ Android Studio - Required for building and installing your app on Android
 ✖ Android SDK - Required for building and installing your app on Android
   - Versions found: 30.0.3, 32.0.0, 32.1.0, 33.0.0
   - Version supported: Not Found
 ✓ ANDROID_HOME

Errors:   3
Warnings: 0

Usage
 › Press f to try to fix issues.
 › Press e to try to fix errors.
 › Press w to try to fix warnings.
 › Press Enter to exit.
```

.bashrc
```
export ANDROID_SDK=$HOME/Android/Sdk
export ANDROID_HOME=$HOME/Android/Sdk
export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools
export JAVA_HOME=/snap/android-studio/119/android-studio/jre
```

## Debug output

<details>
<summary>Debug Console</summary>

```Launching the application
An error occurred while launching the application. Error while executing command 'npm install xdl@59.2.24 @expo/metro-config@0.3.9 --verbose --no-save --global-style': spawn npm ENOENT (error code 303)
```
</details>

<details>
<summary>React Native output channel</summary>

```Checking if this is an Expo app......
....[Error] Error: Error while executing command 'npm install xdl@59.2.24 @expo/metro-config@0.3.9 --verbose --no-save --global-style': spawn npm ENOENT

[Error] Error: Error while executing command 'npm install xdl@59.2.24 @expo/metro-config@0.3.9 --verbose --no-save --global-style': spawn npm ENOENT
```
</details>

## Environment

Please tell us about your system and your project:

```
  System:
    OS: Linux 5.15 Pop!_OS 21.10
    CPU: (24) x64 AMD Ryzen Threadripper 1920X 12-Core Processor
    Memory: 20.02 GB / 31.28 GB
    Container: Yes
    Shell: 5.1.8 - /bin/bash
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.14.0/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
    Watchman: 20220220.232227.0 - /usr/local/bin/watchman
  Managers:
    Apt: 2.3.12 - /usr/bin/apt
    pip3: 20.3.4 - /usr/bin/pip3
  Utilities:
    CMake: 3.18.4 - /usr/bin/cmake
    Make: 4.3 - /usr/bin/make
    GCC: 11.2.0 - /usr/bin/gcc
    Git: 2.32.0 - /usr/bin/git
    FFmpeg: 4.3.1 - /snap/bin/ffmpeg
  Virtualization:
    Docker: 20.10.12 - /usr/bin/docker
  SDKs:
    Android SDK:
      API Levels: 28, 29, 30, 31, 32
      Build Tools: 30.0.3, 32.0.0, 32.1.0, 33.0.0
      System Images: android-31 | Google APIs Intel x86 Atom_64
  IDEs:
    Nano: 5.6.1 - /usr/bin/nano
    VSCode: 1.64.2 - /snap/bin/code
    Vim: 8.2 - /usr/bin/vim
  Languages:
    Bash: 5.1.8 - /usr/bin/bash
    Perl: 5.32.1 - /usr/bin/perl
    Python3: 3.9.7 - /usr/bin/python3
  Databases:
    MySQL: 10.5.13 (MariaDB) - /usr/bin/mysql
    SQLite: 3.32.2 - /home/jeffrey/Android/Sdk/platform-tools/sqlite3
  Browsers:
    Chrome: 97.0.4692.99
```

* React Native Tools extension version: v1.9.1
* Expo SDK version (if applicable): 44

**Comment by RedMickey** [comment]
Hi @JeffreyWardman and thanks for reaching us.

Could you please send us the value of `process.env.PATH` from VS Code for two cases: VS Code launched from the icon launcher and from the terminal using the `code` command?

1. Open VS Code Developer Tools (Click `Help` -> `Toggle Developer Tools`)
1. Open Console tab in it
1. Run the following command `process.env.PATH` and copy the output here
 
The Node path should be in this PATH variable, otherwise this might be the reason of the problem.

**Comment by JeffreyWardman** [comment]
Hi @RedMickey thanks for getting back to me! Hmm. Both are the same; neither include my actual $PATH. What's the best practice to include it in process.env.PATH?

process.env.PATH
```"/home/jeffrey/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin"```

echo $PATH
```/home/jeffrey/.nvm/versions/node/v16.14.0/bin:/home/jeffrey/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/home/jeffrey/Android/Sdk/emulator:/home/jeffrey/Android/Sdk/tools:/home/jeffrey/Android/Sdk/tools/bin:/home/jeffrey/Android/Sdk/platform-tools:/home/jeffrey/Android/Sdk/cmdline-tools/latest/bin:/home/jeffrey/Android/Sdk/emulator:/home/jeffrey/Android/Sdk/tools:/home/jeffrey/Android/Sdk/tools/bin:/home/jeffrey/Android/Sdk/platform-tools```

**Comment by RedMickey** [comment]
@JeffreyWardman If VS Code is launched from the terminal, it inherits all environment variables declared in the `.bashrc` file. If VS Code is launched by means of the UI launcher, [it inherits environment variables from your profile file instead of rc](https://github.com/microsoft/vscode/issues/53529#issuecomment-402798173).

Could you please check the following configurations?

- Check if your `~/.bash_profile` file (or if it doesn't exist, then `~/.profile` file) or `~/.bashrc` contains the NVM declaration

```
# NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
```

- In `~/.bash_profile`:
  - Add the following code to this file to have all settings declared in `~/.bashrc` available: 
  ```
  if [ -f $HOME/.bashrc ]; then
          source $HOME/.bashrc
  fi
  ```
  - In terminal run `source ~/.bash_profile`
  - Restart VS Code editor


- Also please make sure that `~/.profile` contains something like this to forward all settings from `~/.bashrc` :
  ```
  if [ -n "$BASH_VERSION" ]; then
      # include .bashrc if it exists
      if [ -f "$HOME/.bashrc" ]; then
          . "$HOME/.bashrc"
      fi
  fi
  ```
  If there isn't such code in `~/.profile` add it to this file:

  1. Run `nano ~/.profile`
  1. Add the code above and save the changes
  1. Run `source ~/.profile`
  1. Restart VS Code editor

After these changes, I would recommend to log out from the system and log in again. Then, could you please try to launch VS Code from the terminal using the `code` command and try to start Exponent debugging?


Please let us know about your results.

**Comment by JeffreyWardman** [comment]
@RedMickey Legend! Thank you so much! My `~/.bash_profile` was missing the NVM declaration and the addition of the settings declared in `~/.bashrc`. 

Problem solved. Thanks for taking the time to help me :)
