### ISSUE TITLE
Disconnected from the Proxy (Packager) to the React Native application. 

### ISSUE THREAD

**Issue by Mokto** [Microsoft/vscode-react-native#203]
##Actual Behavior
1. App launched ok
2. [vscode-react-native] Established a connection with the Proxy (Packager) to the React Native application
3. [vscode-react-native] Disconnected from the Proxy (Packager) to the React Native application. Retrying reconnection soon...
4. No breakpoint handled

##Expected Behavior
1. Debugging and breakpoints working

##Software versions
- React-Native VS Code extension version: 0.1.3
- VSCode version: 0.10.11 & March Insider
- OS platform and version: Mac OS X El Capitan
- React Native version: 0.23.1

Thanks !

**Comment by digeff** [comment]
@Mokto Could you please answer these questions so we can try to diagnose your issue?

1. Do you get any more messages after 3?
2. Did you start the packager manually outside of VS Code, or inside VS Code?
3. What are the last messages you got on the packager (View --> Toogle Output if you started it or it was started inside VS Code)?
4. Are you running the packager on port 8081? What do you get when you go to localhost:8081/status?
5. When that scenario happens, if you then go to http://localhost:8081/debugger-ui and open chrome, does it work debugging/settings breakpoints there?

Thanks!

**Comment by Mokto** [comment]
1) No but there is an infinite loop with 2) and 3)
2) Inside
3) Receive good requests
```
[4:35:43 PM] <START> request:/index.ios.bundle?platform=ios&dev=true
[4:35:43 PM] <END>   request:/index.ios.bundle?platform=ios&dev=true (23ms)
[4:35:43 PM] <START> request:/index.ios.map?platform=ios&dev=true
[4:35:43 PM] <END>   request:/index.ios.map?platform=ios&dev=true (185ms)
```

4) Yes. I got `packager-status:running`
5) I can't access debugger, it is switching every second between theses two images :

![capture d ecran 2016-04-08 a 16 38 02](https://cloud.githubusercontent.com/assets/5103928/14396918/6ce87624-fda8-11e5-9763-43e408cc0529.png)
![capture d ecran 2016-04-08 a 16 38 04](https://cloud.githubusercontent.com/assets/5103928/14396919/6ced737c-fda8-11e5-9fb7-3d4146f28fac.png)

Thanks !

**Comment by digeff** [comment]
Can you please try this:
1. Get into that same situation where chrome says: "Another debugger is already connected"
2. Stop the VS Code session by pressing the Square red Stop button
3. Refresh the Chrome page again to see if it still says: "Another debugger is already connected"

The reason you are getting the messages 2. and 3. all the time it's because it's trying to connect to the packager, and failing, and retrying again... Given that you are getting the "Another debugger is already connected" message in Chrome I'm wondering if you have another Debugger instance connected to the packager already (Possible another Chrome or VS Code instance, or some hanged processed remaining of those two). When a debugger is already connected to the packager, new connections fail, so that could be an explanation for this behavior.

Could you also try restarting your PC, starting VS Code, starting the packager from the command palette, starting the debugging session, when you get that error close all open Chrome windows, and see if you are still getting that error?

Thanks!

**Comment by Mokto** [comment]
Well when restarting my computer everything works fine.

Thanks for you reactivity and help !

I will be opening more issues regarding breakpoints, it seems that it does not work very well with live reloading.

But one more time, thanks !

**Comment by digeff** [comment]
@Mokto Happy to help!
We appreciate all feedback, so please open all issues you run into, and we'll do our best to help!
