### ISSUE TITLE
Did not support the operator "..." in StyleSheet.create({...})

### ISSUE THREAD

**Issue by LzxHahaha** [Microsoft/vscode-react-native#217]
## Actual Behavior
```
export const styles = StyleSheet.create({
  navBar: {
    ...GlobalStyles.navBar,  // from this statement will report error
    alignItems: 'center'
  },

  searchBox: {
    flex: 1,
  },
});
```

## Software versions
- React-Native VS Code extension version: 0.1.4
- VSCode version: 1.0.0
- OS platform and version: Windows 10 10586.218
- React Native version: 0.23.1

**Comment by hamiltonia** [comment]
Hi @LzxHahaha - this is not an issue with the react-native extension, it is functionality provided by VSCode directly. It looks like this is currently unsupported, as referenced in: https://github.com/Microsoft/vscode/issues/1974

It's also open as a feature request here:
https://github.com/Microsoft/TypeScript/issues/2103

I'm closing this issue here as it's not related directly to the react-native extension, if you would like to follow up on the issue please work with the vscode team directly:
https://github.com/Microsoft/vscode/issues
