### ISSUE TITLE
Cannot attach to running iOS simulator for debugging

### ISSUE THREAD

**Issue by agonzalezjr** [Microsoft/vscode-react-native#246]
## Actual Behavior
1. Can only debug in VS Code if the application is launched from VS Code

## Expected Behavior
1. I expect to be able to attach to a debug app in iOS simulator when the app has been launched from Xcode. This is possible in the NativeScript VSCode plugin and the Chrome Dev Tools do it just fine.

This way we would only have two debug environments: Xcode and VSCode.

## Software versions
- React-Native VS Code extension version: 0.1.4
- VSCode version: 1.2.0
- OS platform and version: Mac OS X 10.11.5
- React Native version: 0.2.0

**Comment by frogcjn** [comment]
VSCode React Native Tool cannot attach to another debugger. It is not like Chrome attachable debugger.

VSCode will use `.vscode/.react/` as a start point.

**Comment by MSLaguana** [comment]
In order for debugging to work, we need to have started the packager. We are considering a workflow where you first run the packager and "prepare to attach" in vscode which sets up a debugging environment, and then you can shake your device and select debug and have it start running the code in a way that vscode can inspect. Does this workflow appeal to you @agonzalezjr or did you have something else in mind?

**Comment by agonzalezjr** [comment]
As long as that let's meet start through Xcode (to debug my native code), and then I shake to enable debug and attach, that would be awesome.

**Comment by agonzalezjr** [comment]
Lets me* (sorry typing from iPhone with autocorrect)

**Comment by MSLaguana** [comment]
I believe that it should, with one caveat: When debugging react-native javascript, because it isn't executing on the device, I believe that native plugin functionality is absent (At least that is our experience from troubleshooting Realm). Would you want to be able to debug your JS interacting with custom native plugins?

I did a small investigation earlier on and I believe it is possible for us to attach to the JS executing on the device (although only if the device is NOT in debug mode!) but only on iOS, and it uses a completely different process to the normal react-native javascript debugging workflow.

**Comment by agonzalezjr** [comment]
Yes I think being able to debug Javascript is the whole point on the request 😄  (since I launched from Xcode, I can already debug Obj-C/Swift from there 😉 )

**Comment by MSLaguana** [comment]
Let me ask this another way to be clear: If you do not use VSCode and you just use the default react-native experience, does debugging in chrome meet your needs? Because that will let you debug your application-logic javascript, but (I believe) it will not let you debug the interaction of your JS with the native side of things.

If debugging with chrome meets your needs then it is relatively simple for us to support that kind of attach ourselves, otherwise I believe that it is possible for iOS and not android and needs some more extensive changes to how debugging works.

**Comment by agonzalezjr** [comment]
Yes it does. That type of simple attach is what I would like to have :)

**Comment by agonzalezjr** [comment]
Thanks!

**Comment by PatoBeltran** [comment]
@agonzalezjr We just merged a PR for attaching to a packager running outside of VSCode (https://github.com/Microsoft/vscode-react-native/pull/250). Does this meet your scenario?

**Comment by agonzalezjr** [comment]
Thanks. Can't wait to try it out!

**Comment by vinayakparmar92** [comment]
@agonzalezjr @PatoBeltran  Can you guys please tell me how this can be done?

**Comment by agonzalezjr** [comment]
@vinayakparmar92 I start my project running from Xcode, then in VSCode, I select "Attach to iOS" in the debug tab. If there isn't an "Attach to iOS" option, it might just mean you need to add a run configuration. This is done by clicking in the gear icon and selecting NativeScript. Good luck!

![image](https://cloud.githubusercontent.com/assets/8965941/25071486/0dfbca94-2287-11e7-8e60-b7f12cac6f29.png)

"Attach to iOS" is in this image where it says "Launch..." noted by "B" 😉
