### ISSUE TITLE
Auto-completing React tags could be life saver

### ISSUE THREAD

**Issue by sercanov** [Microsoft/vscode-react-native#247]
## Actual Behavior
1. Ex. When I need to insert a <View> component, I have to write both opening and closing tags.

## Expected Behavior
1. Auto completion on both tag name and the closing tag.

## Software versions
- React-Native VS Code extension version: 0.1.4
- VSCode version: 1.2
- OS platform and version:  MAC OSX Yosemite
- React Native version: 15.0.2

Example behavior on ; https://atom.io/packages/react

Thanks!

**Comment by mbraude** [comment]
@sercanov thanks for the feedback. We've copied this to our backlog and will get to it as soon as we can.

**Comment by panarasi** [comment]
@sercanov We investigated this issue, and looks like in case of VSCode, you will have to type `<\` to get the end tags. VSCode does not seem to automatically insert the tag, and hence, this extension will not be able to add such a feature. 

I think this would be a great feature to have in VSCode. Can you please open a bug there? Feel free to refer to this bug on that issue. 

Closing this issue since there is not much this extension can do about the feature.
