### ISSUE TITLE
Downloading react-native typings

### ISSUE THREAD

**Issue by nschurmann** [Microsoft/vscode-react-native#252]
The typings provided are not correct. I modified in local the react-native types provided. But this plugins keeps downloading the typings inside the .vcode folder. How can I stop this behaviour?

**Comment by MSLaguana** [comment]
We currently don't check for pre-existing typings, so that's a deficiency in our code that we'll have to address. For a workaround, if you make the typings files read-only after you update them, I believe it should fix the issue in the short term. It may report an error in setting up intellisense, but your update typings should still be reflected in intellisense.

**Comment by PatoBeltran** [comment]
https://github.com/Microsoft/vscode-react-native/pull/262 fixes this. The idea is check for the existence of the `react` or `react-native` directory under `.vscode/typings` and only create them if they don't exist. This way you can modify them without having the extension overwrite the files.
