### ISSUE TITLE
Android Studio needed? 

### ISSUE THREAD

**Issue by forki** [Microsoft/vscode-react-native#268]
The react native getting started tutorial list "android studio" as a prerequisite. Is this needed for this plugin? Is there a list of things I need to install if I want to develop with this plugin?

**Comment by MSLaguana** [comment]
The specific requirement for using this extension is essentially that `react-native run-ios` and `react-native run-android` work, depending on which platform you are trying to work with.

In practice, this means that you must install nodejs, install `react-native` globally, and you have the android SDK and appropriate java JDK installed for android work, or xcode for iOS work. Android studio is not a requirement, but if you do intend to do a lot of work on the native side of things (such as making native extensions) then it may be useful.

**Comment by forki** [comment]
Thanks!

Please consider to change that in the tutorial.

**Comment by panarasi** [comment]
@forki Can you point us to the place in the tutorial where this is referred to ? We should go change that.

**Comment by forki** [comment]
Sure. https://facebook.github.io/react-native/docs/getting-started.html

**Comment by panarasi** [comment]
@forki Looks like this is an issue in the react-native documentation, and the code for that lives here - https://github.com/facebook/react-native/blob/master/docs/GettingStarted.md#dependencies-for-mac--android.

Can you open an issue of PR in the facebook repos ? Closing this issue here since the text is not a part of this repo.
