### ISSUE TITLE
Cannot debug application

### ISSUE THREAD

**Issue by erohin** [Microsoft/vscode-react-native#269]
## Actual Behavior
node --debug-brk=26022 launchReactNative.js ios 9090 ios 'iPhone 6' 
Debugger listening on [::]:26022
[vscode-react-native] [Error : 0901]  Cannot debug application: An error ocurred while handling message: GET_PACKAGER_PORT

## Software versions
- React-Native VS Code extension version: 0.2.0
- VSCode version: 1.3.1
- OS platform and version: OSX 10.11.6
- React Native version: 0.29.0

**Comment by MSLaguana** [comment]
This error message can happen when you try to debug a project which we don't detect as being a react-native project, I just filed an issue on that at https://github.com/Microsoft/vscode-react-native/issues/274.

In my case I hit the issue because I had forgotten to `npm install` in my project, and so there was no react-native node_module installed. Does this apply to you as well?

**Comment by erohin** [comment]
I update VSCode to 1.5.0-insider and debugger is works fine now
