### ISSUE TITLE
Doesn't always stop packager on exit

### ISSUE THREAD

**Issue by BretJohnson** [Microsoft/vscode-react-native#300]
## Actual Behavior
1. Use the "start packager" (or the new "restart packager") command to launch the packager
2. Exit VSCode.
3. Observe if node.exe, hosting the packager process, is still running.  It often is--the issue appears intermittent but frequent.

## Expected Behavior
1. We should always stop the packager, if we started it, on VSCode exit

## Software versions
- React-Native VS Code extension version: 
- VSCode version: 1.4
- OS platform and version: Win10
- React Native version: 0.32

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console): 
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox): 
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):

**Comment by MSLaguana** [comment]
Investigating this, it looks like we're hitting some unfortunate timing constraints when the extension is being torn down.

On windows, when we start the packager via node's `spawn` we get back a process corresponding to `cmd.exe /c react-native start`, rather than directly to the `node react-native-cli.js start` process itself. To make sure that we kill the packager, we try to `taskkill /T` that process, to kill all its descendant processes, but we do this via `exec` which is asynchronous and takes some time. For most scenarios this is fine, and the `Stop Packager` command works. However, during the extension teardown the process hosting the extension is about to be terminated, either when activity stops or within a fairly hard time limit it seems. This leads to the `taskkill` not always completing, and so the descendant node processes remain.
