### ISSUE TITLE
Debugging react-native app that is not directly in the {workspaceRoot}

### ISSUE THREAD

**Issue by faisalil** [Microsoft/vscode-react-native#308]
My setup:
clients/
    reactNativeApp/
       built/
       index.ios.js (renders a component inside /built)
    src/
So I have a step before running my code that will compile the files in /src and copy them to built. 
If I open reactNativeApp/ as my workspaceRoot in VSCode, I can run and debug my application fine. 
What I am trying to do is to open clients/ folder as my working space root. So I can edit files in src/ while running. I tried to use the following launch settings: 

`{
            "name": "Debug iOS",
            "program": "${workspaceRoot}/reactNativeApp/.vscode/launchReactNative.js",
            "type": "reactnative",
            "request": "launch",
            "platform": "ios",
            "target": "iPhone 5s",
            "internalDebuggerPort": 9090,
            "sourceMaps": true,
            "outDir": "${workspaceRoot}/.vscode/.react"
},`

I assumed that if I use this, I would just use the launchReactNative.js file inside the ReactNativeApp and things would work fine. However, that was not the case. I am getting the following error: 

"Could not debug. Unable to set up communication with VSCode react-native extension. Is this a react-native project, and have you made sure that the react-native npm package is installed at the root?"

Do you guys have any idea how to configure things to run when the react-native app is not my workspaceroot?

**Comment by MSLaguana** [comment]
The issue you're hitting there is to do with some internal implementation details of how we integrate the debugger into the rest of the extension. The short of it is, if the folder you have open in VSCode is not detected as a react-native project by us (which we do by checking if `react-native -v` returns a version for react-native, and I believe that in turn is based on there being a `node_modules/react-native` installation) then the debugger won't be able to do things like ensure the react-native packager is started. 

Currently we don't support debugging in a different location to where you have the workspace opened because we base communication between the debugger and the rest of the extension on the path of the project, so if they differ then they won't be able to find each other.

I'm not sure I fully followed your project structure, but one thing that should work, if it suits your workflow, would be to open 2 different VSCode windows; one in the `reactNativeApp` folder which you use to launch the debugger, and one in the parent folder or whichever folder you want to edit. Any files which are modified should still be picked up by the packager since that isn't something we do in our extension specifically.

**Comment by mbraude** [comment]
We do have a backlog item to address this and allow RN projects outside the root.
