### ISSUE TITLE
Allow starting packager in a sub folder

### ISSUE THREAD

**Issue by panarasi** [Microsoft/vscode-react-native#312]
We could expose a property in launch.json that could be used to indicate the top level of a ReactNative project. This could be used to launch the ReactNative packager, and the exponent packager.

**Comment by satya164** [comment]
Would be perfect for my use case. Thank you. Loving VSCode!

**Comment by panarasi** [comment]
@MSLaguana What do you think about this proposal ? Doable ?

**Comment by MSLaguana** [comment]
Definitely possible, but we'll have to make sure to refer to this property everywhere, including when we set up interprocess communication from the debugger back to the VSCode extension

**Comment by panarasi** [comment]
@MSLaguana Awesome, thanks. Let us copy this over to the backlog and schedule it as a work item.

**Comment by alsorokin** [comment]
@MSLaguana @panarasi do you think `settings.json` would be a better place for such an option? Because we would need it at extension activate time and not at debugger launch time?

**Comment by MSLaguana** [comment]
Yes, I think settings.json is the correct place for this, especially since we cannot allow multiple values specified in different launch.json entries (without a lot of extra effort).

We may also need to change the triggers for our extension activating, since if the root does not have a package.json but some subfolder does then currently we won't even try to start.

**Comment by haitaoli** [comment]
I would like to have this feature too. In my project the main RN code is in a sub directory, and there are a bunch of js files in another directory. I mostly need debugger support because I have to run the packager separately. With atom/nuclide I can add multiple folders into the project so that's not a problem. But VSCode doesn't support that.

**Comment by panarasi** [comment]
@haitaoli We are currently looking into this.
