### ISSUE TITLE
React Native Packager Slow reloads

### ISSUE THREAD

**Issue by calebmer** [Microsoft/vscode-react-native#329]
The React Native Packager is much slower to create to a build when run in visual studio code then when the packager is run outside VS Code (even with debug mode on). Often it will take seconds to reload the app. Whereas when run in a separate terminal window reloads are relatively snappy. This makes iterative development with live reload very tricky.

When seeing the packager output, the builds are fairly snappy, 30-170ms. It takes much longer for the app to finish reloading however.
## Software versions
- React-Native VS Code extension version: 0.2.1
- VSCode version: 1.6.1
- OS platform and version: MacOS Sierra
- React Native version: 0.35.0

**Comment by vladimir-kotikov** [comment]
@terbooter FYI, this is something I'd like you to take into account

**Comment by panarasi** [comment]
@vladimir-kotikov  I don't think that this is a new feature. This looks like a bug to me that we should investigate.

**Comment by vladimir-kotikov** [comment]
Ok, we did some profiling of the code that gets executed each time when app reloads and compared it with reload cycle in when debugging in Chrome. The timings are ~500 ms/reload for Chrome (this is very approximate number as we weren't able to profile this process) and ~2500 ms/reload when debugging using the extension. The measurements were done using empty app, created with `react-native init` and latest RN version (0.47.1)

Below is a typical picture of what's happening at that time:

![image](https://user-images.githubusercontent.com/3857604/29312562-a820464a-81be-11e7-84e7-a98e2c8150c3.png)

The two intervals where debug adapter spends most of the time are:
1. ~2100-2600 ms - most of this time debug adapter does basically nothing
2. ~3600-4600 ms - at this interval debug adapter is 100% busy processing bundle's sourcemap

The first ~500 ms pause is caused by chrome-debug-core library trying to connect to debuggee process. It looks like the architecture of node inspector protocol requires several attempts for debugger to figure out proper WebSocket connection params before connecting to debuggee and this causes this delay.

As for the second interval - this delay is caused by `source-map` module internals parsing  source map for react-native bundle. Parsing operation itself syncronous and consists of simple math and arrays sorting which makes it impossible to do this work asyncronously.

As a result we spend additional ~1.5 seconds on every reload compared to debugging in Chrome and probably won't be able to fix this problem either on our side or in chrome-debug core

**Comment by vladimir-kotikov** [comment]
@panarasi, thoughts?

Also /cc'ing @roblourens as most of these time gaps are caused by underlying chrome-debug-core code and he might have other ideas about what's happening there

**Comment by roblourens** [comment]
After it attaches to Chrome, it downloads the sourcemaps and parses them as they come in, and if they are large, this could take time. I'm not aware of any random time wastage but maybe it could be optimized.

**Comment by vladimir-kotikov** [comment]
@roblourens thanks for the input. That's quite understandable that parsing large SM's (~4Mb in our case) takes time.

It also would be great if you can comment on delays when chrome-debug-core attaches to node process, is that expected behavior?

**Comment by roblourens** [comment]
I can't tell what's going on in the profile. It attaches as quickly as possible, it isn't waiting for anything.
