### ISSUE TITLE
Feature request: Intellisense for propTypes

### ISSUE THREAD

**Issue by cbrevik** [Microsoft/vscode-react-native#343]
Not sure if this belongs here or with the main VSCode repository. My apologies if it's in the wrong place. Anyway, I have a suggestion:

At the moment, when developing React Native apps in VSCode, I get intellisense for React Native components (typed via react-native.d.ts), and JavaScript which has JSDoc. 

Since I am writing `propTypes` anyway on my own components (for debug checks on set values, and "sort of" docs for other developers), it would be great to have intellisense for them as well.

Not sure if this is within the scope of this extension, but thought I'd throw it out there anyway. Thanks for all the great work! I use this extension daily. 👍

**Comment by MSLaguana** [comment]
If you write your react-native code in typescript then you can do this already: the `Component` class from react is actually `Component<P, S>` which accepts template parameters for the props and state types, so you can write `class MyClass extends Component<PropsType, StateType> {...` and get the intellisense support.

I'm not sure whether we can provide the same access in a plain JS project.

**Comment by MSLaguana** [comment]
I just spoke with some of the typescript team, and I have a partial solution for you, and they have some ideas for improvements later on.

For now, here's what I suggest:
1.  Define your props/state types somewhere, e.g. `typings/react-native.d.ts`. Make sure that this location is referenced by the `tsconfig.json` or `jsconfig.json` at the root of your project (By default any `.d.ts` files under the root and not in a dot-folder should be included).
    *  For example, I might define `interface IProps {foo: string}` and `interface IState { bar: number}` in `typings/react-native.d.ts`.
2. In your js file where you define a new component, add the generic definition like so:
  ```
export default class testapp extends Component<IProps, IState> {
```
3. You should now have intellisense on `this.props` and `this.state` within that class:
![image](https://cloud.githubusercontent.com/assets/14098340/20501390/920c72d6-afee-11e6-9adc-6d7d9b1cc46a.png)

You may get errors pointing at the `Component<Props, State>` in future since it isn't legal JS, but the default react-native babel configuration includes removing flow types, and this syntax is common between flow and typescript so it will be removed as part of compilation.

In future, the typescript language service may support additional JSDoc features which would let you specify a JSDoc comment to provide the generic parameters rather than using the TS syntax directly in the code.

Does this match what you were looking for?

**Comment by cbrevik** [comment]
Well sort of, what I originally wanted was intellisense outside of the class, not inside of the class. In other words if I make a `Button` component, then I want intellisense for the props of `Button` in other classes/components that use it.

I also tried the thing you're describing here. But it doesn't seem like VSCode (or the extension maybe?) is picking it up. I even tried putting the definition in its own file at root:

```js
import * as React from 'react';
import * as ReactNative from 'react-native';

declare namespace Core {
    // Button
    interface ButtonProps extends React.Props<Button> {
        disabled?: boolean,
        style?: ReactNative.ViewStyle,
        textContainerStyle?: ReactNative.ViewStyle,
        textStyle?: ReactNative.ViewStyle,
        text?: string,
        onPress: Function,
    }

    export class Button extends React.Component<ButtonProps, {}>{ }
}

export = Core;
```

Ideally, it would be cool to get `propTypes` intellisense even for pure JS files, since I don't think TypeScript works great (yet) with React Native and its packager. But I can understand that this issue would not be a priority, so feel free to close it in that case.

**Comment by FrancescoLorenzetti84** [comment]
If you defined your props as an interface, you can use the spread operator to do:

    <MyComponent {...{ myProperty: "its value" } as IMyComponentProps} />

In this case, intellisense will suggest you the available members of the interface, and their type.

**Comment by mohsen1** [comment]
We made a convertor that uses propTypes to create actual TypeScript interfaces:

https://github.com/lyft/react-javascript-to-typescript-transform

Hope it's helpful for your issue

**Comment by vladimir-kotikov** [comment]
Closing this one as we're not maintaining own RN typings anymore and requests like this are more approriate to be filled against DT repo: https://github.com/DefinitelyTyped/DefinitelyTyped/issues
