### ISSUE TITLE
Not supported with apisauce v0.8.0+

### ISSUE THREAD

**Issue by Amurmurmur** [Microsoft/vscode-react-native#393]
Debug JS Remotely feature on iOS throws exception: vscode-react-native-0.2.5/node_modules/q/q.js:155

When got back to apisauce 0.8.0 worked fine again. 
When Remote debugger is off with apisauce 0.10.0+, it works fine too.

**Comment by matrosov-nikita** [comment]
@Amurmurmur, I was able to reproduce this issue using vsmobile.vscode-react-native 0.2.5. It seems to me that problem is interaction between react-native runtime and extension's debug engine. We've used node2-debug engine since 0.3.0. Could you please try to upgrade extension to 0.3.0 and let us know whether it resolves your problem?

**Comment by Amurmurmur** [comment]
@matrosov-nikita All just cool. Thank you so much for your fast response, and kindness support!! Greatly appreciate it!!
