### ISSUE TITLE
What to set jsCodeLocation to for iOS debugging?

### ISSUE THREAD

**Issue by lukecwilliams** [Microsoft/vscode-react-native#483]
This is an issue with the README.md documentation, with this line:

> "Change the jsCodeLocation IP in your app using the steps detailed here."

Two issues:
1. What should jsCodeLocation be set *to*?  The readme just says to "set" it but there doesn't appear to be guidance on what the value should be.

2. The link for setting jsCodeLocation no longer includes such instructions.  I found alternate instructions here: https://gist.github.com/almost/898a829d5197c69d29b0

Thank you!

**Comment by vladimir-kotikov** [comment]
@lukecwilliams thanks for reporting. This is an issue with documentation we'll need to address. This recipe doesn't seem to be actual anymore since RN on iOS is now able to determine packager URL automagically using `jsBundleURLForBundleRoot` method(see for example https://github.com/panarasi/ReactNativeTS/blob/master/ios/ReactNativeTS/AppDelegate.m#L21)

Also linking relevant PR: https://github.com/Microsoft/vscode-react-native/pull/447
