### ISSUE TITLE
IntelliSense for StyleSheet is not working #306

### ISSUE THREAD

**Issue by shoegazerwithak** [Microsoft/vscode-react-native#513]
## Actual Behavior
1. No autocomplete by typing in stylesheet, no autocomplete by pressing Ctrl+Space

![screenshot_20170816_173426](https://user-images.githubusercontent.com/11088992/29368843-85335848-82a9-11e7-835a-a87267819561.png)

(although it does autocomplete properties if there are values like alignItems present)

![screenshot_20170816_174737](https://user-images.githubusercontent.com/11088992/29369337-019f5264-82ab-11e7-9f2a-d1254dee1cca.png)

2. No autocomplete for values at all
![screenshot_20170816_173330](https://user-images.githubusercontent.com/11088992/29368856-8e3dc888-82a9-11e7-9b93-60d9915adb45.png)

## Expected Behavior
1. Autocomplete of stylesheet properties either by typing or by pressing Ctrl+Space
2. Autocomplete of stylesheet property values

## Software versions
- React-Native VS Code extension version: 0.4.0
- VSCode version: 1.15.0
- OS platform and version: Linux dalvikd 4.4.0-91-generic #114-Ubuntu SMP Tue Aug 8 11:56:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux, KDE neon 5.10
- NodeJS version: 7.10.1
- React Native version: 0.47.1

**Comment by vladimir-kotikov** [comment]
Thanks for reporting @shoegazerwithak. Unfortunately as I mentioned in #499 this is likely an issue with typescript engine that doesn't yield completions under some specific circumstances.

Also since we don't manage typings in this extension and completely rely on typescript and VSCode I doubt we can do anything here - I believe that [Microsoft/Typescript](https://github.com/Microsoft/TypeScript/issues) repository would be a better place to file this issue.

**Comment by vladimir-kotikov** [comment]
I'm going to close this one - feel free to reopen if you think that this is a problem with this extension
