### ISSUE TITLE
newbie intellisense install not working on MAC and Windows

### ISSUE THREAD

**Issue by j2l** [Microsoft/vscode-react-native#521]
I think I miss a step somewhere when configuring react native tools.
I already have other extensions working fine:
![image](https://user-images.githubusercontent.com/65325/29772945-596a07f6-8bfb-11e7-8eb5-3eaf2da7241a.png)

## Actual Behavior
No intellisense, both on mac and windows
For example, trying "AppRegistry" like in the GIF example:
![image](https://user-images.githubusercontent.com/65325/29773060-fdd88010-8bfb-11e7-8a8d-528125461920.png)

## Expected Behavior
have intellisense on expo project

## Software versions
- React-Native VS Code extension version: 
- VSCode version: 1.15.1
- OS platform and version: mac, windows 10
- NodeJS version: 6.3.1
- React Native version: 0.45.1 (cli: 2.0.1)

**Comment by vladimir-kotikov** [comment]
@j2l, thanks for reporting

Intellisense for ReactNative is not controlled by this extension anymore and I afraid that README instructions regarding setting it up are mostry irrelevant. Ideally since Intellisense for JSX provided by VSCode typescript engine it should work out-of-the box even if you don't have this extension installed.

One of ideas apart from the bug in either VSCode or TS engine, this might be possibly caused by other installed extensions (I see that you have 2 extensions for Flow installed) conflicting with tsserver or adding some configurations, preventing typescript engine to provide completions. Can you please try disabling those and see if it helps?

Also since we don't manage typings in this extension and completely rely on typescript and VSCode I doubt we can do anything here - I believe that [Microsoft/Typescript](https://github.com/Microsoft/TypeScript/issues) repository would be a better place to file this issue.
