### ISSUE TITLE
No output in debug console if react-native is not in path

### ISSUE THREAD

**Issue by DVSoftware** [Microsoft/vscode-react-native#545]
## Actual Behavior
1. When trying to attach or run react native project, nothing happens and nothing is written to the debug console

## Expected Behavior
1. Some sort of warning that react-native command is not found

## Software versions
- React-Native VS Code extension version: 0.4.2
- VSCode version: Insiders
- OS platform and version: MacOS 10.12.6
- NodeJS version: 8.6.0
- React Native version: 0.48.2

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
```

**Comment by iTOYS** [comment]
Hi @DVSoftware 
This fixed in #530
If `react-native` not installed in project root, you will get error in DEBUG CONSOLE

`Could not debug. Unable to set up communication with VSCode react-native extension. Is this a react-native project, and have you made sure that the react-native npm package is installed at the root?`

New version of the extension will be released soon.
