### ISSUE TITLE
IntelliSense for StyleSheet using flow

### ISSUE THREAD

**Issue by tafelito** [Microsoft/vscode-react-native#678]
## Actual Behavior
1. Same issue as #306 
2. Go to definition doesn't work when either when trying to navigate to specific style

## Expected Behavior
1. support IntelliSense for StyleSheet when using flow

## Software versions
- React-Native VS Code extension version:  0.6.6
- VSCode version: 1.22.1
- OS platform and version: MacOS 10.13.4
- React Native version:  0.54.2

Side note: I disabled builtin typescript plugins as they have conflicts when using flow

**Comment by ruslan-bikkinin** [comment]
Hi @tafelito and thanks for reaching us. Could you please clarify what plugins did you disable? Also any screenshots, code samples that illustrates your problem will be much appreciated.

**Comment by tafelito** [comment]
I disabled both TS builtin plugins and installed Flow extension

![image](https://user-images.githubusercontent.com/5973652/39217795-8eaf5fb4-47ef-11e8-9cd9-415e4778b829.png)

And I'm using 
![image](https://user-images.githubusercontent.com/5973652/39217826-adc8e596-47ef-11e8-888c-c0aec0824a80.png)

Just by creating a new project with react-native init and adding flow-bin dependency it's possible to reproduce this. 

when I try to use the autocomplete for styles, there are no suggestions at all

![image](https://user-images.githubusercontent.com/5973652/39217970-4565f51a-47f0-11e8-94c0-b2bccaa36cfb.png)

Also If I try to navigate to a style definition by doing cmd+click in a style prop, it doesn't do anything compared to doing the same on top of the styles object, it does go to the definition in that case

**Comment by ruslan-bikkinin** [comment]
@tafelito did you try [these instructions](https://github.com/Microsoft/vscode-react-native/blob/master/doc/intellisense.md) from our documentation? If not, please, try to (also no need to disable builtin plugins for typescript and javascript manually in this case).

Please let us know if it helps.

**Comment by tafelito** [comment]
Yes that's how I did it but using flow-bin locally instead of globally. Isn't that the reason to use flow.useNPMPackagedFlow=true? (I tried global too just in case but it didn't work either). 
I disabled builtin TS packages because that's what it says on the extension docs. And if you don't do it, definitions get duplicated. So if you try to go to definition it shows you multiple definitions instead of actually going.

![image](https://user-images.githubusercontent.com/5973652/39253897-f30d09fc-4876-11e8-83d6-a2fb61fc00d9.png)

**Comment by ruslan-bikkinin** [comment]
Hi again @tafelito. 

I am afraid that I was wrong mentioning about [this documentation section](https://github.com/Microsoft/vscode-react-native/blob/master/doc/intellisense.md) because it's seem to be outdated. Actually, `vscode-react-native` doesn't control intelisense stufffor React Native anymore because it's handled by builtin VS Code extension now. You can check it for yourself by removing *React Native Tools* extension (as well as *Flow Language Support*) completely and trying, for example, to call code-hinting or navigating inside RN SDK files - it will work. 

I believe you should file this issue to [https://github.com/flowtype/flow-for-vscode](flow-for-vscode) or [https://github.com/Microsoft/vscode](vscode) instead as it's better place for solving it now.
