### ISSUE TITLE
"Could not debug. Starting tunnels timed out" occurred during debugging with Expo

### ISSUE THREAD

**Issue by jackjj12** [Microsoft/vscode-react-native#708]
## Actual Behavior
1. I have do the work under below introduction.
 https://github.com/Microsoft/vscode-react-native/blob/master/doc/expo.md
2. however, when I debug it it shows " Could not debug. Starting tunnels timed out", I do not know why

## Expected Behavior
1. give us a detailed docs of how to configuration with expo or crna. not the below https://github.com/Microsoft/vscode-react-native/blob/master/doc/expo.md , I am really confusing with this document. a simple example of crna or expo is prefer.
2. Thank u.V S CODE is really great. Thank u

## Software versions
- React-Native VS Code extension version: 
- VSCode version: 
- OS platform and version: 
- NodeJS version: 
- React Native version: 

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
PASTE OUTPUT HERE
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
PASTE OUTPUT HERE
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
PASTE OUTPUT HERE
```

**Comment by jackjj12** [comment]
Hi @ruslan-bikkinin  I have read your message about the software version. In fact my expo and xde is okay. I have used xde to start my app and use'exp start', all these methods is okay. I could run my app with these methods. but I still have the problem above. My XDE version is newest. I can not debug with vs code. And I have to debug with chrome browser.

**Comment by jackjj12** [comment]
Okay, I have noticed that the error happend on both expo and vscode. its my mistake maybe. It maybe a problem for expo. 
But when the problem happened in expo . I can still view my app with my expo tools.

But in vs code ,just can not debug. maybe you can download a expo or crna and set up enviroment to test it.
below is the out put from vscode 
same problem come with expo. 
[Warning] Warning: 'antd-mobile' dependency is not installed.
Warning: 'babel-plugin-module-resolver' dependency is not installed.
Warning: 'expo' dependency is not installed.
Warning: 'react' dependency is not installed.
Warning: 'react-native' dependency is not installed.
Warning: 'react-native-charts-wrapper' dependency is not installed.
Warning: 'react-native-elements' dependency is not installed.
Warning: 'react-native-i18n' dependency is not installed.
Warning: 'react-navigation' dependency is not installed.

If there is an issue running your project, please run `npm install` in e:\Demo\demo-detach\react-native-simple-demo and restart.

No issue with project-adb-reverseNo issue with project-adb-reverseLoading dependency graph, done.
[Error] Error starting tunnel: Error: Starting tunnels timed out

[Error] Error starting tunnel: Error: Starting tunnels timed out

[Error] Error: Starting tunnels timed out

Error starting tunnel: Error: Starting tunnels timed out

**Comment by jackjj12** [comment]
If you can share me a configuration with expo or a example for us maybe in github or others. it is better.

**Comment by ruslan-bikkinin** [comment]
@jackjj12 
Here is my demo project that I've prepared using `exp init rn708-expo` command: https://github.com/ruslan-bikkinin/rn708-expo
In order to debug you should do the following:
1. Clone `rn708-expo` repo and run `npm i` inside project directory.
2. Install Expo app on your device/simulator if you haven't done this before (the version of expo app must be supported by expo sdk version that app is using).
3. Open demo project `rn708-expo` in VS Code.
4. Start debugging using `Run In Exponent` configuration.
5* If after opening your project in Expo App debugger stuck at `[Info] Enable JS Debugging` just shake your device/simulator and select 'Debug JS Remotely' to enable debugging. 

According to logs you have shared, seems to be your project is lacking of 'antd-mobile', 'babel-plugin-module-resolver' and other dependencies. I believe you should run `npm i` inside root of your app and try to debug again.

**Comment by ruslan-bikkinin** [comment]
Hi @jackjj12 could you please let me know did you have a chance to look at this?

**Comment by jackjj12** [comment]
Really Sorry to response to you so late. it works. but there are another problem of can not debug serveral page. and generate a bug of "process.send". maybe something of the new version rn.
please note it . and I will colse this issue.
