### ISSUE TITLE
Intellisense doesn't work with ES6 import?

### ISSUE THREAD

**Issue by Tom29** [Microsoft/vscode-react-native#710]
I'm stucking with this trouble for days.

`import abc from './abc'` doesn't work, the `abc.xyz()` or any function inside it will not be suggested.
Even the file `abc.js` will not be suggested

I have to use `abc = required('./abc.js')` and things work fine.
Both file suggestion and method will be available

I've tried to added `jsconfig.json` and force it to use `"module":"es6"` but didn't work either.

Already got `react native tools` installed.
Couldn't get it work eventually.

Vscode Version 1.23.1 (1.23.1)
All extensions are up to date

**Comment by ruslan-bikkinin** [comment]
Hi @Tom29 and thanks for reaching us. React Native Tools extension is not responsible for IntelISense for React Native anymore due to VS Code have taken control over it completely. I suggest you to refer your question to [VS Code issue tracker](https://github.com/Microsoft/vscode/issues) as it is a better place for it.
