### ISSUE TITLE
Possible Regression in 0.6.11 in setting projectRoot

### ISSUE THREAD

**Issue by jas99** [Microsoft/vscode-react-native#724]
@ruslan-bikkinin 
There might be also regression, in latest release, debugger started complaining of root project, 
`"react-native-tools.projectRoot": "./packages/client"`
```
OS: darwin x64
Adapter node: v7.9.0 x64
vscode-chrome-debug-core: 3.17.3
Could not debug. Seems to be that you are trying to debug from within directory that is not a React Native project root.
If so, please, follow these instructions: https://github.com/Microsoft/vscode-react-native/blob/master/doc/customization.md#project-structure.
```

**Comment by ruslan-bikkinin** [comment]
Hi @jas99 thanks for submitting this. Does your project use `lerna`? Could you please share with us directory structure of workspace that you uses?

**Comment by ruslan-bikkinin** [comment]
@jas99 Just tried to reproduce issue using lerna project with such project structure:
`Project724/packages/clients/<RN project content here>`. I opened `Project724` in VS Code, then added `.vscode/settings.json` file with `"react-native-tools.projectRoot": "./packages/clients"` content and could debug my app without any troubles. So, I will be waiting for details for your side to be able help you.

**Comment by jas99** [comment]
I figured it out, my settings.json file was ending with trailing comma and I guess maybe not parsed and hence giving the error since property didn't set. But I guess there should some notification of this error in json or something.

**Comment by ruslan-bikkinin** [comment]
@jas99 Actually, on debugger side we are using [this](https://github.com/Microsoft/vscode-react-native/blob/master/src/debugger/nodeDebugWrapper.ts#L239) "tricky" method to read from `settings.json` because we can't use VS Code api for it. Seems to be that parser comes to `catch` block due to incorrect json in your case. I believe we can improve this part by providing error report to the user as you suggested. Thanks for pointing to this!

**Comment by jas99** [comment]
That will be indeed helpful.
Thx
