### ISSUE TITLE
Unable to resolve module ../../assets/xxx.png from js file

### ISSUE THREAD

**Issue by khpang94** [Microsoft/vscode-react-native#921]
I don't know what is the problem, is it the react - native version cause the error to be happen.

Issue as per below, i want import the image to a javascript.
Image actual path :  C:\Users\kim\Desktop\Boss\boss\assets
Js actual path : C:\Users\kim\Desktop\Boss\boss\screens\LoginRegister

Unable to resolve module ../../assets/Boss.png from C:\Users\kim\Desktop\Boss\boss\screens\LoginRegister\Logo.js: The module ../../assets/Boss.png could not be found from C:\Users\kim\Desktop\Boss\boss\screens\LoginRegister\Logo.js. Indeed, none of these files exist:
  * Boss.png
  * C:\Users\kim\Desktop\Boss\boss\assets\Boss.png\index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)

ABI30_0_0RCTFBQuickPerformanceLoggerConfigureHooks
ABI31_0_0RCTFBQuickPerformanceLoggerConfigureHooks
<redacted>
<redacted>
<redacted>
<redacted>
<redacted>
CFRunLoopRunSpecific
GSEventRunModal
UIApplicationMain
Exponent
<redacted>

**Comment by ruslan-bikkinin** [comment]
hi @khpang94 and thanks for reaching us. Are you experiencing this while running via `react-native run-android`?

**Comment by khpang94** [comment]
Thanks for answering me, i have resolved it by replacing a new image for "Boss.png". I not sure why the original one is spoiled, because it able to start in another PC.

**Comment by vi07** [comment]
> Thanks for answering me, i have resolved it by replacing a new image for "Boss.png". I not sure why the original one is spoiled, because it able to start in another PC.

The same happened to me. Did you find out why this problem occurred?

**Comment by emperorvicky** [comment]
The issue you're encountering is because the import paths are case-sensitive in most environments, including Node.js and React Native. For example Your import statement for Boss is using lowercase "ibadan.jpg", while the actual import statement should match the exact filename, which is likely different in casing.

1.). Check the Exact Filename and Path: Ensure that the filenames and their paths exactly match what you have in your file system. For example, if the actual filename is Boss.png, then the import statement should be:

`import Boss from "../../assets/Boss.png";`

2.) Double-check that the file extensions match exactly (e.g., .jpg, .jpeg, .png).

Then you shoudn't have that error again
